// GENERATED by scripts/build-migrations.ts — do not edit.
// Source: drizzle/0000_wakeful_blue_shield.sql, 0001_email_accounts.sql

export const MIGRATIONS: string[] = [
  "CREATE TABLE \"holdings\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"player_id\" integer NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"shares\" numeric(18, 6) NOT NULL,\n\t\"cost_basis\" numeric(16, 2) NOT NULL,\n\tCONSTRAINT \"holdings_player_symbol\" UNIQUE(\"player_id\",\"symbol\")\n);",
  "CREATE TABLE \"instruments\" (\n\t\"symbol\" text PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"sector\" text NOT NULL,\n\t\"blurb\" text NOT NULL,\n\t\"badge\" text NOT NULL,\n\t\"role\" text NOT NULL\n);",
  "CREATE TABLE \"orders\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"player_id\" integer NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"side\" text NOT NULL,\n\t\"amount\" numeric(16, 2) NOT NULL,\n\t\"shares\" numeric(18, 6) NOT NULL,\n\t\"price\" numeric(16, 4) NOT NULL,\n\t\"filled_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"players\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"handle\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"initials\" text NOT NULL,\n\t\"pin_hash\" text NOT NULL,\n\t\"cash\" numeric(16, 2) NOT NULL,\n\t\"joined_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"players_handle_unique\" UNIQUE(\"handle\")\n);",
  "CREATE TABLE \"quotes\" (\n\t\"symbol\" text PRIMARY KEY NOT NULL,\n\t\"price\" numeric(16, 4) NOT NULL,\n\t\"prev_close\" numeric(16, 4) NOT NULL,\n\t\"fetched_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"portfolio_snapshots\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"player_id\" integer NOT NULL,\n\t\"as_of\" date NOT NULL,\n\t\"total_value\" numeric(16, 2) NOT NULL,\n\t\"seeded\" text DEFAULT 'false' NOT NULL,\n\tCONSTRAINT \"snapshot_player_day\" UNIQUE(\"player_id\",\"as_of\")\n);",
  "ALTER TABLE \"holdings\" ADD CONSTRAINT \"holdings_player_id_players_id_fk\" FOREIGN KEY (\"player_id\") REFERENCES \"public\".\"players\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"holdings\" ADD CONSTRAINT \"holdings_symbol_instruments_symbol_fk\" FOREIGN KEY (\"symbol\") REFERENCES \"public\".\"instruments\"(\"symbol\") ON DELETE no action ON UPDATE no action;",
  "ALTER TABLE \"orders\" ADD CONSTRAINT \"orders_player_id_players_id_fk\" FOREIGN KEY (\"player_id\") REFERENCES \"public\".\"players\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"portfolio_snapshots\" ADD CONSTRAINT \"portfolio_snapshots_player_id_players_id_fk\" FOREIGN KEY (\"player_id\") REFERENCES \"public\".\"players\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "CREATE INDEX \"orders_player_idx\" ON \"orders\" USING btree (\"player_id\",\"filled_at\");",
  "-- Real accounts: email + password instead of a picked test handle and a PIN.\n--\n-- Hand-written rather than generated, because it has to clear the seeded test\n-- crew before `email` can be NOT NULL — and it has to do that exactly once.\n-- The DO block keys off `pin_hash` still existing, so re-running setup after a\n-- real account exists is a no-op instead of a wipe.\nDO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'players' AND column_name = 'pin_hash'\n  ) THEN\n    DELETE FROM \"players\";\n  END IF;\nEND $$;",
  "ALTER TABLE \"players\" ADD COLUMN IF NOT EXISTS \"email\" text;",
  "ALTER TABLE \"players\" ADD COLUMN IF NOT EXISTS \"password_hash\" text;",
  "ALTER TABLE \"players\" ALTER COLUMN \"email\" SET NOT NULL;",
  "ALTER TABLE \"players\" ALTER COLUMN \"password_hash\" SET NOT NULL;",
  "DO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'players_email_unique') THEN\n    ALTER TABLE \"players\" ADD CONSTRAINT \"players_email_unique\" UNIQUE (\"email\");\n  END IF;\nEND $$;",
  "ALTER TABLE \"players\" DROP COLUMN IF EXISTS \"handle\";",
  "ALTER TABLE \"players\" DROP COLUMN IF EXISTS \"pin_hash\";"
];
