// GENERATED by scripts/build-migrations.ts — do not edit.
// Source: drizzle/0000_wakeful_blue_shield.sql

export const MIGRATIONS: string[] = [
  "CREATE TABLE \"holdings\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"player_id\" integer NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"shares\" numeric(18, 6) NOT NULL,\n\t\"cost_basis\" numeric(16, 2) NOT NULL,\n\tCONSTRAINT \"holdings_player_symbol\" UNIQUE(\"player_id\",\"symbol\")\n);",
  "CREATE TABLE \"instruments\" (\n\t\"symbol\" text PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"sector\" text NOT NULL,\n\t\"blurb\" text NOT NULL,\n\t\"badge\" text NOT NULL,\n\t\"role\" text NOT NULL\n);",
  "CREATE TABLE \"orders\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"player_id\" integer NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"side\" text NOT NULL,\n\t\"amount\" numeric(16, 2) NOT NULL,\n\t\"shares\" numeric(18, 6) NOT NULL,\n\t\"price\" numeric(16, 4) NOT NULL,\n\t\"filled_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"players\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"handle\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"initials\" text NOT NULL,\n\t\"pin_hash\" text NOT NULL,\n\t\"cash\" numeric(16, 2) NOT NULL,\n\t\"joined_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"players_handle_unique\" UNIQUE(\"handle\")\n);",
  "CREATE TABLE \"quotes\" (\n\t\"symbol\" text PRIMARY KEY NOT NULL,\n\t\"price\" numeric(16, 4) NOT NULL,\n\t\"prev_close\" numeric(16, 4) NOT NULL,\n\t\"fetched_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
  "CREATE TABLE \"portfolio_snapshots\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"player_id\" integer NOT NULL,\n\t\"as_of\" date NOT NULL,\n\t\"total_value\" numeric(16, 2) NOT NULL,\n\t\"seeded\" text DEFAULT 'false' NOT NULL,\n\tCONSTRAINT \"snapshot_player_day\" UNIQUE(\"player_id\",\"as_of\")\n);",
  "ALTER TABLE \"holdings\" ADD CONSTRAINT \"holdings_player_id_players_id_fk\" FOREIGN KEY (\"player_id\") REFERENCES \"public\".\"players\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"holdings\" ADD CONSTRAINT \"holdings_symbol_instruments_symbol_fk\" FOREIGN KEY (\"symbol\") REFERENCES \"public\".\"instruments\"(\"symbol\") ON DELETE no action ON UPDATE no action;",
  "ALTER TABLE \"orders\" ADD CONSTRAINT \"orders_player_id_players_id_fk\" FOREIGN KEY (\"player_id\") REFERENCES \"public\".\"players\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"portfolio_snapshots\" ADD CONSTRAINT \"portfolio_snapshots_player_id_players_id_fk\" FOREIGN KEY (\"player_id\") REFERENCES \"public\".\"players\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "CREATE INDEX \"orders_player_idx\" ON \"orders\" USING btree (\"player_id\",\"filled_at\");"
];
