import {
  date,
  index,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

/* ---------------------------------------------------------------------------
   Money is numeric, never float. Shares are fractional to six places, because
   the design promises a play "can be $5 or $500K" — whole shares would make
   most stocks unbuyable at $5.
--------------------------------------------------------------------------- */

export const players = pgTable("players", {
  id: serial("id").primaryKey(),
  handle: text("handle").notNull().unique(),
  name: text("name").notNull(),
  initials: text("initials").notNull(),
  /** scrypt hash as `salt:derivedKey`, both hex. */
  pinHash: text("pin_hash").notNull(),
  cash: numeric("cash", { precision: 16, scale: 2 }).notNull(),
  joinedAt: timestamp("joined_at", { withTimezone: true }).notNull().defaultNow(),
});

export const instruments = pgTable("instruments", {
  symbol: text("symbol").primaryKey(),
  name: text("name").notNull(),
  /** "stock" | "etf" — US listings only, per the design brief. */
  kind: text("kind").notNull(),
  sector: text("sector").notNull(),
  /** The one-line context the discover rows show under the name. */
  blurb: text("blurb").notNull(),
  /** Two-letter badge, e.g. NV for NVIDIA. */
  badge: text("badge").notNull(),
  /** Palette role the badge is tinted with. */
  role: text("role").notNull(),
});

export const holdings = pgTable(
  "holdings",
  {
    id: serial("id").primaryKey(),
    playerId: integer("player_id")
      .notNull()
      .references(() => players.id, { onDelete: "cascade" }),
    symbol: text("symbol")
      .notNull()
      .references(() => instruments.symbol),
    shares: numeric("shares", { precision: 18, scale: 6 }).notNull(),
    /** Total dollars paid in, so unrealised P/L is value - costBasis. */
    costBasis: numeric("cost_basis", { precision: 16, scale: 2 }).notNull(),
  },
  (t) => [unique("holdings_player_symbol").on(t.playerId, t.symbol)]
);

export const orders = pgTable(
  "orders",
  {
    id: serial("id").primaryKey(),
    playerId: integer("player_id")
      .notNull()
      .references(() => players.id, { onDelete: "cascade" }),
    symbol: text("symbol").notNull(),
    /** "buy" | "sell" */
    side: text("side").notNull(),
    amount: numeric("amount", { precision: 16, scale: 2 }).notNull(),
    shares: numeric("shares", { precision: 18, scale: 6 }).notNull(),
    /** The price the fill actually used — server-decided, never client-sent. */
    price: numeric("price", { precision: 16, scale: 4 }).notNull(),
    filledAt: timestamp("filled_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("orders_player_idx").on(t.playerId, t.filledAt)]
);

/** 15-minute quote cache — the delay the UI promises the player. */
export const quotes = pgTable("quotes", {
  symbol: text("symbol").primaryKey(),
  price: numeric("price", { precision: 16, scale: 4 }).notNull(),
  prevClose: numeric("prev_close", { precision: 16, scale: 4 }).notNull(),
  fetchedAt: timestamp("fetched_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * One row per player per day. This is what makes % return over a month,
 * quarter or year answerable — competition is on percentage gain, and the
 * stack itself never resets, so a baseline per period is required.
 */
export const snapshots = pgTable(
  "portfolio_snapshots",
  {
    id: serial("id").primaryKey(),
    playerId: integer("player_id")
      .notNull()
      .references(() => players.id, { onDelete: "cascade" }),
    asOf: date("as_of").notNull(),
    totalValue: numeric("total_value", { precision: 16, scale: 2 }).notNull(),
    /** true for the history generated by the seed, false once earned live. */
    seeded: text("seeded").notNull().default("false"),
  },
  (t) => [unique("snapshot_player_day").on(t.playerId, t.asOf)]
);
