/**
 * Bakes the generated SQL migrations into a TypeScript module.
 *
 * Serverless functions don't reliably ship sibling folders, so `/api/setup`
 * can't read `drizzle/*.sql` at runtime. This turns them into an importable
 * array instead. Re-run after `npm run db:generate`.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = join(import.meta.dirname, "..", "drizzle");
const files = readdirSync(DIR).filter((f) => f.endsWith(".sql")).sort();

const statements = files.flatMap((f) =>
  readFileSync(join(DIR, f), "utf8")
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter(Boolean)
);

writeFileSync(
  join(import.meta.dirname, "..", "api", "_lib", "migrations.ts"),
  `// GENERATED by scripts/build-migrations.ts — do not edit.\n` +
    `// Source: drizzle/${files.join(", ")}\n\n` +
    `export const MIGRATIONS: string[] = ${JSON.stringify(statements, null, 2)};\n`
);

console.log(`baked ${statements.length} statements from ${files.length} file(s)`);
